# Generated by Django 2.0.9 on 2024-07-09 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20240706_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='image',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
